language: node_js
node_js:
  - "node"
jobs:
  include:
    - script: bash .bin/build-site.sh
      name: "Build nulinks-site"
    - script: bash .bin/test-common.sh
      name: "Test nulinks-common"
deploy:
  skip_cleanup: true
  provider: script
  script: bash .bin/deploy.sh
  on: 
    branch: master
