language: node_js
node_js:
  - "node"
jobs:
  include:
    - stage: test
      script: bash .bin/build-site.sh
      script: bash .bin/test-common.sh
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on: 
    branch: master