language: node_js
node_js:
  - "node"
stages:
  - compile
  - test
  - deploy
jobs:
  include:
    - stage: compile
      name: "Build nulinks-site"
      script: bash .bin/build-site.sh
    - stage: test
      name: "Test nulinks-common"
      script: bash .bin/test-common.sh
    - stage: deploy
      name: "Deploy to S3"
      script: /bin/true
      deploy:
        skip_cleanup: true
        provider: script
        script: bash .bin/deploy.sh "part1"
        on: 
          branch: master
    - stage: deploy
      name: "Deploy to Chrome Web Store"
      script: /bin/true
      deploy:
        skip_cleanup: true
        provider: script
        script: bash .bin/deploy.sh "part2"
        on: 
          branch: master
