name: Deploy
on: 
  push:
    branches:
      - master

jobs:
  deploy-s3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install and build site
      run: |
        npm install
        cd nulinks-site
        npm run build
      env:
        CI: true
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: './nulinks-site/build'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy-cws:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name:  build extension
      run: |
        # Install
        npm install
        cd nulinks-site
        npm run build
        cd ..
        
        # Install jq
        apt-get install --no-install-recommends -y jq
        
        BUILD_NUM=$(git rev-list --count HEAD --first-parent)
        
        pushd . > /dev/null

        # Set up the folder structure that we'll need
        mkdir -p /tmp/nulinks/nulinks-extension

        # Copy extension files
        cp -Rp nulinks-extension/* /tmp/nulinks/nulinks-extension

        # Copy common files
        # Remove the symbolic link
        rm /tmp/nulinks/nulinks-extension/nulinks-common
        # Copy files
        mkdir -p /tmp/nulinks/nulinks-extension/nulinks-common
        cp -Rp nulinks-common/* /tmp/nulinks/nulinks-extension/nulinks-common

        # Copy site build files
        mkdir -p /tmp/nulinks/nulinks-extension/pages
        cp -Rp nulinks-site/build/* /tmp/nulinks/nulinks-extension/pages
        # Remove site's manifest
        rm /tmp/nulinks/nulinks-extension/pages/manifest.json

        # Remove other extra files
        rm /tmp/nulinks/nulinks-extension/nulinks-common/package.json
        rm /tmp/nulinks/nulinks-extension/nulinks-common/package-lock.json
        rm -f /tmp/nulinks/nulinks-extension/nulinks-common/junit.xml
        rm -rf /tmp/nulinks/nulinks-extension/nulinks-common/node_modules
        rm -rf /tmp/nulinks/nulinks-extension/nulinks-common/test

        # Add the build number to the version in the manifest
        jq ".version+=\".$BUILD_NUM\"" manifest.json

        # Build the zip file
        cd /tmp/nulinks
        zip -r nulinks-extension.zip nulinks-extension

        # Restore the CWD
        popd > /dev/null

        # Copy the zip back here
        cp /tmp/nulinks/nulinks-extension.zip .
      env:
        CI: true
    - uses: actions/upload-artifact@master
      with:
        name: built-extension-zip
        path: nulinks-extension.zip
